//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConcert_WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class categoriasevento
    {
        public int PK_categoriasEvento { get; set; }
        public int FK_CATEGORIASEVENTO_EVENTOS { get; set; }
        public int FK_CATEGORIASEVENTO_CATEGORIAS { get; set; }
        public int FK_CATEGORIASEVENTO_BANDAS { get; set; }
    
        public virtual bandas bandas { get; set; }
        public virtual categorias categorias { get; set; }
        public virtual eventos eventos { get; set; }
    }
}
