//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConcert_WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class comentarios
    {
        public int PK_comentarios { get; set; }
        public string comentario { get; set; }
        public int calificacion { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public int FK_COMENTARIOS_BANDAS { get; set; }
        public string FK_COMENTARIOS_USUARIOS { get; set; }
        public int FK_COMENTARIOS_ESTADOS { get; set; }
    
        public virtual bandas bandas { get; set; }
        public virtual estados estados { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
