//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConcert_WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class eventos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eventos()
        {
            this.categoriasevento = new HashSet<categoriasevento>();
            this.votos = new HashSet<votos>();
        }
    
        public int PK_eventos { get; set; }
        public string nombreEve { get; set; }
        public string ubicacion { get; set; }
        public System.DateTime fechaInicio { get; set; }
        public System.DateTime fechaFinal { get; set; }
        public Nullable<System.DateTime> finalVotacion { get; set; }
        public string comida { get; set; }
        public string transporte { get; set; }
        public string servicios { get; set; }
        public int FK_EVENTOS_PAISES { get; set; }
        public int FK_EVENTOS_ESTADOS { get; set; }
        public int FK_EVENTOS_TIPOSEVENTOS { get; set; }
        public Nullable<int> FK_EVENTOS_BANDAS_CHEF { get; set; }
    
        public virtual bandas bandas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<categoriasevento> categoriasevento { get; set; }
        public virtual estados estados { get; set; }
        public virtual paises paises { get; set; }
        public virtual tiposeventos tiposeventos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<votos> votos { get; set; }
    }
}
