//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConcert_WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class generosusuario
    {
        public int PK_generosUsuario { get; set; }
        public int FK_GENEROSUSUARIO_GENEROS { get; set; }
        public string FK_GENEROSUSUARIO_USUARIOS { get; set; }
    
        public virtual generos generos { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
