//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConcert_WebService
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class myconcertEntities : DbContext
    {
        public myconcertEntities()
            : base("name=myconcertEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bandas> bandas { get; set; }
        public virtual DbSet<canciones> canciones { get; set; }
        public virtual DbSet<categorias> categorias { get; set; }
        public virtual DbSet<categoriasevento> categoriasevento { get; set; }
        public virtual DbSet<estados> estados { get; set; }
        public virtual DbSet<generos> generos { get; set; }
        public virtual DbSet<generosbanda> generosbanda { get; set; }
        public virtual DbSet<generosusuario> generosusuario { get; set; }
        public virtual DbSet<integrantes> integrantes { get; set; }
        public virtual DbSet<paises> paises { get; set; }
        public virtual DbSet<tiposeventos> tiposeventos { get; set; }
        public virtual DbSet<tiposusuarios> tiposusuarios { get; set; }
        public virtual DbSet<universidades> universidades { get; set; }
        public virtual DbSet<votos> votos { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<eventos> eventos { get; set; }
        public virtual DbSet<comentarios> comentarios { get; set; }
    }
}
