//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyConcert_WebService
{
    using System;
    using System.Collections.Generic;
    
    public partial class votos
    {
        public int PK_votos { get; set; }
        public int valor { get; set; }
        public int FK_VOTOS_BANDAS { get; set; }
        public int FK_VOTOS_EVENTOS { get; set; }
        public int FK_VOTOS_CATEGORIAS { get; set; }
        public string FK_VOTOS_USUARIOS { get; set; }
    
        public virtual bandas bandas { get; set; }
        public virtual categorias categorias { get; set; }
        public virtual usuarios usuarios { get; set; }
        public virtual eventos eventos { get; set; }
    }
}
